function* genFunc() {
    throw new Error('Problema!');
}

const genObj = genFunc();
genObj.next(); // Lan√ßa um erro: "Error: Problema!"
